"""Add fs_webauthn_user_handle to users

Revision ID: 5e91516126ab
Revises: c41d52d02da3
Create Date: 2026-01-18 15:33:10.955753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e91516126ab'
down_revision: Union[str, Sequence[str], None] = 'c41d52d02da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fs_webauthn_user_handle', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['fs_webauthn_user_handle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fs_webauthn_user_handle')
    # ### end Alembic commands ###
